### DISCUSSION TITLE
Import memory into Wasm compiled from Grain

### DISCUSSION THREAD

**Discussion by radkomih** [grain-lang/grain#1364] [Help] [answered]
Hi there,
Is it possible to compile module written in Grain and produce Wasm module that looks similar to the one below?
*  import host provided memory
* import host provided functions
* export linker specific globals
 
```
Type: wasm
Size: 210 B
Imports:
  Functions:
    "env"."ext_func": [] -> []
  Memories:
    "env"."memory": not shared (20 pages..)
  Tables:
  Globals:
Exports:
  Functions:
    "inter_func": [I32, I32] -> [I64]
  Memories:
  Tables:
  Globals:
    "__data_end": I32 (constant)
    "__heap_base": I32 (constant)
```
