### ISSUE TITLE
Grain produces duplicate imports

### ISSUE THREAD

**Issue by ashtonmeuser** [grain-lang/grain#1850]
macOS 13.3.1
Grain 0.5.13

Duplicate import functions declared in module.

## Repro:
1. Start with a directory with only a single `main.gr` file containing `export let test2 = () => print("A")`
2. Compile with `grain compile main.gr`
3. Inspect the module imports & exports e.g. `wasmer inspect main.gr.wasm`

Note the duplicate imports (see below).
```
Type: wasm
Size: 197.7 KB
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "test2": [] -> []
    "_start": [] -> []
  Memories:
    "memory": not shared (64 pages..)
  Tables:
  Globals:
```

Edit: Running compiler with `--release` never produces thees duplicates.
