### ISSUE TITLE
Investigate release action issue

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#2286]
Got this cryptic error during the last release:
> .github/workflows/release.yml (Line: 36, Col: 12): could not get operand for index access: Error from function 'fromJSON': empty input

It refers to the preview job:
```
  build-preview:
    name: Build preview binaries
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release-pr }}
    uses: ./.github/workflows/build-js.yml
    with:
      os: ubuntu-latest
      ref: ${{ fromJSON(needs.release-please.outputs.release-pr).headBranchName }}
```

Not sure what's up, but thankfully this job wasn't in the path of the release.
